export const API = {
  register: "auth/register",
  login: "auth/login",
  generateTwoStepCodeQr: "auth/generate-google-auth-code",
  forgotPassword: "auth/forgot-password",
  resetPassword: "auth/reset-password",
  verifyEmail: "auth/verify-email",
  verifyPhoneNumber: "auth/verify-otp",
  sendTokenForEmailVerification: "auth/send-verification-email",
  sendOtpForPhoneNumVerification: "auth/send-otp",
  getCryptoPricing:
  "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin%2Cethereum%2Ctron%2Cbinance-coin-wormhole%2Ctether&vs_currencies=inr",
  getUserDetails: "users/auth-user-info",
  saveUserDetails: (userId) => `users/${userId}`,
  getBankDetails: "bank",
  getAdminBankDetails: "bank/get-admin-bank-details",
  saveBankDetails: "bank",
  createOrder: "orders",
  getUserWalletDetails: "wallets",
  getOrderDetails: "orders/user-orders",
};
